config/routes.rb
Rails.application.routes.draw do

  require "resque_web"

  mount ResqueWeb::Engine => "/resque_web"

  devise_for :users, :controllers => {:registrations => "administracion/registrations"}

  unauthenticated :user do
    root to: redirect('/users/sign_in')
  end

  authenticated :user do

    root to: "users#index", as: :inicio_root


    resources :users

    # /comentarios/35/ImputacionActividad
    get '/comentarios/:comentable_id/:comentable_type', to: 'comentarios#index', as: 'comentarios'
    resources :comentarios, only: [] do
      post '/:comentable_id/:comentable_type', to: 'comentarios#create', on: :collection #create
      get '/:comentable_id/:comentable_type', to: 'comentarios#edit', on: :member, as: :edit #edit
      put :update, on: :member, as: :update #update
      patch :update, on: :member #update
      delete :destroy, on: :member #delete
    end

    devise_scope :user do
      put "/users/:id/reactivate" => "administracion/registrations#reactivate", as: :reactivate_user_registration
    end

  end

end

app/views/menu/_admin_breadcrum.html.erb
<ol class="breadcrumb">
  <li ><a href="<%= inicio_root_path %>"><%= t("home") %></a></li>
  <li class="active" ><a href="<%= users_path %>"><%= t("users_admin.users_control") %></a></li>
</ol>

app/views/menu/_admin_currentaction.html.erb
<div class="page-header-content">
  <div class="page-title">
    <h1 class="content-group text-thin no-top-margin no-bottom-margin">
      <% if @current and @accion.present? %>
              <%= @accion + ' ' +  @current  %>
          <% elsif @title.present? %>
        <%= @title %>
      <% end %>
    </h1>
  </div>
</div>

app/views/menu/_confirm_modal.html.erb
<div class="modal fade" id="<%= dialog_elements[:id].to_s %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><%= dialog_elements[:titulo].to_s %></h4>
      </div>
      <div class="modal-body">
        <%= dialog_elements[:texto].to_s %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default btn-aceptar-modal" data-dismiss="modal"><%= t('botones.aceptar') %></button>
        <button type="button" class="btn btn-primary btn-cancelar-modal"><%= t('botones.cancelar') %></button>
      </div>
    </div>
  </div>
</div>

app/views/menu/_flash_messages.html.erb
<% model = self.controller.get_model_for_errors %>
<div class="form-group flash_messages">
  <%if flash.any? %>

      <% flash.each do |key, value| %>
          <div class="
                <% if key.to_s != "notice" %>
                  alert alert-danger
                <% else %>
                  alert alert-success
                <% end %>
                            ">
            <%= value %>
          </div>
      <% end %>
  <% end %>

  <% if model.try(:errors) %>
      <div id="error_explanation" class="alert alert-danger">
        <h2><%= t("no_se_guarda", table: model.class.model_name.human, error: pluralize( model.errors.count, "error") )%></h2>
        <ul>
          <% model.errors.full_messages.each do |message| %>
              <li><%= message %></li>
          <% end %>
        </ul>
      </div>

  <% end %>
</div>

app/views/menu/_footer.html.erb
<div class="footer text-muted">
  &copy; 2015. <a href="#">DMSTI</a>
</div>

app/views/menu/_home_breadcrum.html.erb
<div class="breadcrumb-line">
  <ol class="breadcrumb">
    <li role="presentation">
      <i class="icon-home2 position-left"></i>
      <%= link_to t("home"), inicio_root_path , role: "menuitem", tabindex: "-1" %>
    </li>
    <%if @parent%>
        <li role="presentation">
          <%= link_to @parent.capitalize, @parent_path , role: "menuitem", tabindex: "-1" %>
        </li>
    <% end %>
    <% if @current_pl %>
        <li class="active" >
          <%= link_to @current_pl, @current_path , role: "menuitem", tabindex: "-1" %>
        </li>
    <% end %>
  </ol>
</div>

app/views/menu/_left_menu.html.erb
<div class="sidebar sidebar-main bg-dark-blue-800">
  <div class="sidebar-content">

    <!-- User menu -->
    <div class="sidebar-user">
      <div class="category-content">
        <div class="media">
          <div class="media-left media-middle">
            <a href="#" class=""><span class="letter-icon"></span></a>
          </div>
          <div class="media-body">
            <span class="media-heading text-semibold"></span>
            <div class="text-size-mini text-muted">

            </div>
          </div>

          <div class="media-right media-middle">
            <ul class="icons-list">
              <li>
                <a href="#"><i class="icon-cog3"></i></a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <!-- /user menu -->
    <!-- Main navigation -->
    <div class="sidebar-category sidebar-category-visible">
      <div class="category-content no-padding">
        <ul class="navigation navigation-main navigation-accordion">

          <!-- Main -->
          <li class="navigation-header"><span><%= t('main')%></span> <i class="icon-menu" title="Main pages"></i></li>
          <!-- /main -->

        </ul>
      </div>
    </div>
    <!-- /main navigation -->

  </div>
</div>

app/views/menu/_menu.html.erb
<div class="navbar navbar-inverse navbar-fixed-top bg-dark-blue-700 border-bottom-blue-300">
  <div class="navbar-header">
    <a class="navbar-brand text-thin" href="/"> SKELETON </a>

    <ul class="nav navbar-nav pull-right visible-xs-block">
      <li><a data-toggle="collapse" data-target="#navbar-mobile"><i class="icon-tree5"></i></a></li>
      <li><a class="sidebar-mobile-main-toggle"><i class="icon-paragraph-justify3"></i></a></li>
    </ul>
  </div>

  <div class="navbar-collapse collapse" id="navbar-mobile">
    <% if user_signed_in? %>
            <ul class="nav navbar-nav">
              <li><a class="sidebar-control sidebar-main-toggle hidden-xs"><i class="icon-paragraph-justify3"></i></a></li>
            </ul>
        <% end %>

    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
          <li class="dropdown dropdown-user">
            <a class="dropdown-toggle" data-toggle="dropdown">
              <%= image_tag 'image.png'%>
              <span><%= current_user.username%></span>
              <i class="caret"></i>
            </a>

            <ul class="dropdown-menu dropdown-menu-right">
              <li><a href="#"><i class="icon-user-plus"></i> My profile</a></li>
              <!--<li><a href="#"><i class="icon-coins"></i> My balance</a></li>-->
              <!--<li><a href="#"><span class="badge badge-warning pull-right">58</span> <i class="icon-comment-discussion"></i> Messages</a></li>-->
              <li class="divider"></li>
              <li>
                    <i class="icon-cog5"></i> <%= t('empleados.configuracion') %>
              </li>
              <li>
                <a href="<%= destroy_user_session_path %>" data-method="delete" ><i class="icon-switch2"></i> Logout</a></li>
            </ul>
          </li>
      <% end %>
    </ul>
  </div>
</div>