config/routes.rb
Rails.application.routes.draw do

  require "resque_web"

  mount ResqueWeb::Engine => "/resque_web"

  devise_for :users, :controllers => {:registrations => "administracion/registrations"}

  unauthenticated :user do
    root to: redirect('/users/sign_in')
  end

  authenticated :user do

    root to: "users#index", as: :inicio_root


    resources :users

    # /comentarios/35/ImputacionActividad
    get '/comentarios/:comentable_id/:comentable_type', to: 'comentarios#index', as: 'comentarios'
    resources :comentarios, only: [] do
      post '/:comentable_id/:comentable_type', to: 'comentarios#create', on: :collection #create
      get '/:comentable_id/:comentable_type', to: 'comentarios#edit', on: :member, as: :edit #edit
      put :update, on: :member, as: :update #update
      patch :update, on: :member #update
      delete :destroy, on: :member #delete
    end

    devise_scope :user do
      put "/users/:id/reactivate" => "administracion/registrations#reactivate", as: :reactivate_user_registration
    end

  end

end

app/models/comentario.rb
class Comentario < ActiveRecord::Base

  belongs_to :comentable, polymorphic: true
  belongs_to :user

end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :get_comentario, only: [:destroy, :edit, :update]

  def index
    get_comentarios(params[:comentable_id], params[:comentable_type], :create)
  end

  def create
    @comentario = Comentario.create({
                                        texto: params[:comentario][:texto],
                                        comentable_id: params[:comentable_id],
                                        comentable_type: params[:comentable_type],
                                        user_id: current_user.id
                                    })
    redirect_to comentarios_path(@comentario.comentable_id.to_s, @comentario.comentable_type.to_s), format: 'js'
  end

  def edit
    get_comentarios(params[:comentable_id], params[:comentable_type], :update)
  end

  def update
    @comentario.update({
                           texto: params[:comentario][:texto],
                           user_id: current_user.id
                       })

    redirect_to comentarios_path(@comentario.comentable_id.to_s, @comentario.comentable_type.to_s), format: 'js'
  end

  def destroy
    @comentario.destroy

    # get_comentarios(@comentario.comentable_id.to_s, @comentario.comentable_type.to_s, :create)
    redirect_to comentarios_path(@comentario.comentable_id.to_s, @comentario.comentable_type.to_s), format: 'js', status: :see_other
  end

  private

  def get_comentario
    @comentario = Comentario.find(params[:id])
  end


  def get_comentarios(comentable_id, comentable_type, accion)
    @accion = accion
    @comentarios = Comentario.where(comentable_id: comentable_id, comentable_type: comentable_type)
    if @accion == :create
      @comentario = Comentario.new(comentable_id: comentable_id,comentable_type: comentable_type)
    end

    @comentarios.where('NOT `check` AND user_id != ' + current_user.id.to_s).update_all(check: true)

    respond_to do |format|
      format.js {
        render file: '/comentarios/modal_comentarios.js.erb', layout: false
      }

    end
  end
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/views/comentarios/_comentario.html.erb
<% empleado = comentario.user.empleado %>
<% if (empleado == current_user.empleado) %>
    <li class="media reversed">
      <div class="media-body">
        <div class="media-content">
          <%= comentario.texto %>
          <i class="icon-checkmark4 <%= comentario.check ? 'check_leido' : 'check_recibido'%>"></i>
        </div>
        <span class="media-annotation display-block mt-10">
          <%= l(comentario.updated_at.to_date,format: :fecha_ficha) %>
          <% if !comentario.check %>
            <%= link_to comentario_path(comentario), method: :delete, data: { confirm: t('acciones.confirmacion') }, remote: true do %>
              <i class="icon-trash position-right text-muted"></i>
              <% end %>
              <%= link_to edit_comentario_path(comentario, comentario.comentable_id, comentario.comentable_type), remote: true do %>
              <i class="icon-pencil5 position-right text-muted"></i>
              <% end %>
          <% end %>
        </span>
      </div>

      <div class="media-right">
        <a href="#" class="btn bg-blue btn-rounded btn-icon btn-lg">
          <span class="letter-icon"><%= empleado.nombre[0].capitalize + empleado.apellidos[0].capitalize %></span>
        </a>
      </div>
    </li>
<% else %>
    <li class="media">
      <div class="media-left">
        <a href="#" class="btn bg-teal btn-rounded btn-icon btn-lg">
          <span class="letter-icon"><%= siglas_empleado(empleado) %></span>
        </a>
      </div>

      <div class="media-body">
        <div class="media-content">
          <%= comentario.texto %>
          <i class="icon-checkmark4 <%= comentario.check ? 'check_leido' : 'check_recibido'%>"></i>
        </div>
        <span class="media-annotation display-block mt-10">
          <%= l(comentario.updated_at.to_date,format: :fecha_ficha) %>
          <% if !comentario.check %>
            <%= link_to comentario_path(comentario), method: :delete, data: { confirm: t('acciones.confirmacion') }, remote: true do %>
              <i class="icon-trash position-right text-muted"></i>
              <% end %>
              <%= link_to edit_comentario_path(comentario, comentario.comentable_id, comentario.comentable_type), remote: true do %>
              <i class="icon-pencil5 position-right text-muted"></i>
              <% end %>
          <% end %>
        </span>
      </div>
    </li>
<% end %>

app/views/comentarios/_form_comentario.html.erb
<%= form_for ((@accion == :update) ? @comentario : :comentario), url: {action: @accion }, remote: true do |f| %>
    <%= f.text_area :texto, { :class => "form-control content-group flotante", :rows => "3", :cols => "1", :placeholder => t('comentarios.introduce_comentario')}%>
    <div class="row">
      <div class="col-xs-6">
        <ul class="icons-list icons-list-extended mt-10">
          <li><a href="#" data-popup="tooltip" title="Send photo" data-container="body"><i class="icon-file-picture"></i></a></li>
          <li><a href="#" data-popup="tooltip" title="Send video" data-container="body"><i class="icon-file-video"></i></a></li>
          <li><a href="#" data-popup="tooltip" title="Send file" data-container="body"><i class="icon-file-plus"></i></a></li>
        </ul>
      </div>
      <div class="col-xs-6 text-right">
        <% if @accion != :create %>
            <button type="submit" class="btn bg-teal-400 btn-labeled btn-labeled-right"><b><i class="icon-circle-right2"></i></b><%=t('botones.actualizar')%></button>
            <%= link_to comentarios_path(@comentario.comentable_id, @comentario.comentable_type), remote: true  do %>
                <button type="button" class="btn btn-danger btn-labeled btn-labeled-right "><b><i class="icon-circle-right2"></i></b><%=t('botones.cancelar')%></button>
            <% end %>
        <% else %>
            <button type="submit" class="btn bg-teal-400 btn-labeled btn-labeled-right"><b><i class="icon-circle-right2"></i></b><%=t('botones.enviar')%></button>
        <% end %>
      </div>
    </div>
<% end %>

app/views/comentarios/_modal_body.html.erb
<ul class="media-list chat-list content-group">
  <li class="media date-step">
    <span><%= t('comentarios.hoy')%></span>
  </li>
  <% @comentarios.each_with_index  do |comentario, i| %>
      <%if comentario.id.present? %>
          <%= render '/comentarios/comentario', {i: i, comentario: comentario}%>
      <% end %>
  <% end %>
</ul>
<%= render 'comentarios/form_comentario' %>

app/views/comentarios/_modal_comentarios.html.erb
<div class="modal fade" id="comentarios" tabindex="-1" role="dialog" aria-labelledby="comentarios-label">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title text-primary text-thin" id="comentarios-label"><%= t("comentarios.titulo") %></h3>
      </div>
      <div class="modal-body">
       <%= render 'comentarios/modal_body' %>
      </div>
    </div>
  </div>
</div>

app/views/comentarios/modal_comentarios.js.erb
if (($('#comentarios').length == 0) || (!$('#comentarios').hasClass('in'))) {
    console.log('if');
    $('#container-modal').append('<%= j render "/comentarios/modal_comentarios", { objeto: @objeto, accion: @accion }  %>');
    $('#comentarios').modal('show');
}else{
    console.log('else');
    $('#comentarios').find('.modal-body').empty().html('<%= j render "/comentarios/modal_body", { objeto: @objeto, accion: @accion }  %>');
}
setTimeout(function(){
    $(".media-list").animate({ scrollTop: $(".media-list").last().prop("scrollHeight")}, 1000);
},700);