config/routes.rb
Rails.application.routes.draw do

  require "resque_web"

  mount ResqueWeb::Engine => "/resque_web"

  devise_for :users, :controllers => {:registrations => "administracion/registrations"}

  unauthenticated :user do
    root to: redirect('/users/sign_in')
  end

  authenticated :user do

    root to: "users#index", as: :inicio_root


    resources :users

    # /comentarios/35/ImputacionActividad
    get '/comentarios/:comentable_id/:comentable_type', to: 'comentarios#index', as: 'comentarios'
    resources :comentarios, only: [] do
      post '/:comentable_id/:comentable_type', to: 'comentarios#create', on: :collection #create
      get '/:comentable_id/:comentable_type', to: 'comentarios#edit', on: :member, as: :edit #edit
      put :update, on: :member, as: :update #update
      patch :update, on: :member #update
      delete :destroy, on: :member #delete
    end

    devise_scope :user do
      put "/users/:id/reactivate" => "administracion/registrations#reactivate", as: :reactivate_user_registration
    end

  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum rol: { becario: 0, super_admin: 1, no_logeado: -1, admin: 2}
  #before_save :create_initial_accesibilidad



  has_many :comentarios

  attr_accessor :login , :status

  scope :becarios, -> { where(rol: roles[:becario])}
  scope :activos, -> { where(deleted_at: nil) }

  validates :username,
            :presence => true,
            :uniqueness => {
                :case_sensitive => false
            }
  validates :email,
            :presence => true,
            :uniqueness => {
                :case_sensitive => false
            }

  # si el deleted_at está presente, el status es :down.
  # si el deleted_at es nulo, el status es :activo.
  def active?
    deleted_at.blank?
  end

  def down?
    deleted_at.present?
  end

  # soft delete action
  def soft_delete!
    update_attributes( deleted_at: Time.current )
  end

  def soft_delete
    assign_attributes( deleted_at: Time.current )
  end

  # reactivate action
  def reactivate!
    update_attributes( deleted_at: nil )
  end

  def reactivate
    assign_attributes( deleted_at: nil )
  end


  # función para crear los permisos
  def build_or_modify_initial_accesibilidad

    if self.rol.present?
      rol = self.rol
    else
      rol = User.roles[:no_logeado]
      self.rol = rol
    end


  end

  def create_or_modify_initial_accesibilidad
    build_or_modify_initial_accesibilidad
  end

  # ensure user account is active
  def active_for_authentication?
    super && !deleted_at
  end

  # custom message for a deleted account
  def inactive_message
    !deleted_at ? super : :deleted_account
  end


  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete( :login )
      where( conditions.to_h ).where( [ "lower(username) = :value", { :value => login.downcase } ] ).first
    else
      where( conditions.to_h ).first
    end
  end

  def no_cliente(atributos)
    atributos[:cliente_id].blank?
  end

  protected

  # Se llama sólo con la creación. Está en el after_save
  def create_initial_accesibilidad
    if self.rol.blank?
      create_or_modify_initial_accesibilidad
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  before_filter :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update]
  before_action :set_form_index, only: :index
  before_action :set_form_new, only: :new
  before_action :set_form_edit, only: :edit
  before_action :set_form_show, only: :show
  respond_to :html, :json
  layout "bodycontainer_layout"
  def index
    authorize User
    @users = User.all
    respond_with(@users)
  end

  def show
    authorize @user
    respond_with(@users)
  end

  def edit
    authorize User
    @clientes_asignables=Cliente.activos
  end

  def update
    authorize @user
    @user.update(user_params)
    if @save_result = @user.save
      mensaje = User.model_name.human + ' ' + t('acciones.actualizado')
      redirect_to users_path, flash: { notice: mensaje }
    else
      respond_with(@user)
    end
  end
  def get_model_for_errors
    @user if @save_result == false
  end

  private
  def body_literals
    super
    model_name = t('activerecord.models.users.one')
    @current = (params[:action] == "index") ? t('activerecord.models.users.other').downcase : model_name
    @current_pl = t('activerecord.models.users.other')
    @current_path = @current_path
  end

  def set_form_index
    @accion = t('acciones.listado')
  end

  def set_form_new
    @accion = t('acciones.nuevo')
  end

  def set_form_edit
    @accion = t('acciones.editar')
  end

  def set_form_show
    @title = t('acciones.datos')
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :rol, users_clientes_attributes: [:id, :cliente_id, :user_id, :_destroy])
  end



end

app/views/users/_form.html.erb
<fieldset>
  <%= nested_form_for @user, html: {:class => 'form-horizontal'} do |f| %>
      <%= render layout:  "layouts/formcontainer_layout" do %>
          <div class="row">
            <div class="form-group col-md-6 col-sm-offset-1 col-md-offset-0 col-sm-10">
              <%= f.label :username, { :class => 'control-label col-sm-4 align-right'} %>
              <div class="col-sm-8 col-xs-12 ">
                <%= f.text_field :username, { :class => 'form-control' }%>
              </div>
            </div>
            <div class="form-group col-md-6 col-sm-offset-1 col-md-offset-0 col-sm-10">
              <%= f.label :email, { :class => 'control-label col-sm-4 align-right'} %>
              <div class="col-sm-8 col-xs-12 ">
                <%= f.text_field :email, { :class => 'form-control' }%>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="form-group col-md-6 col-sm-offset-1 col-md-offset-0 col-sm-10">
              <%= f.label :rol, { :class => 'control-label col-sm-4 align-right'} %>
              <div class="col-sm-8 col-xs-12 ">
                <%= f.select :rol, t('user.rol').map{|x,y| [ y.capitalize, y ]}, {include_blank: true}, {class: 'select'} %>
                <%#= f.number_field :rol, { :class => 'form-control' }%>
              </div>
            </div>
          </div>


            <div class="row">
              <div class="form-group ">
                <h2 class="control-label js-etiqueta-uc col-xs-2 col-xs-offset-1 text-thin " style = "display:<%= f.object.clientes.size > 0 ?  "block" : "none" %>" ><%= t('activerecord.models.cliente.other') %></h2>
              </div>
            </div>

            <div class="actions col-xs-12 mt-15">
              <div class="text-right">

            <%= f.fields_for :users_clientes do |uc| %>

                <div class="form-group col-sm-10 col-sm-offset-1 col-md-6 col-md-offset-10">
                  <%= uc.label :cliente_id, { :class => 'control-label col-sm-4 align-right'}%>
                  <div class="col-sm-6 col-xs-12"> <!-- @clientes_asignables son los clientes a los cuales se les puede asignar el clientes actual, en principio todos-->
                    <%= uc.collection_select :cliente_id, @clientes_asignables, :id, :opcion, {include_blank: true}, {class: 'js-select js-select-disable ', :onchange => 'select_disable_observers_change();'} %>
                  </div>
                  <div class="col-xs-12 col-sm-1 align-right">
                    <%= uc.link_to_remove raw('<i class="glyphicon glyphicon-trash"></i>'), class:"btn bg-danger-600 js-eliminar-uc", onclick: 'select_disable_wait(); control_etiqueta_uc_disable( this );' %>
                  </div>
                </div>
                <div class="js-ajuste-row row", style="display:none">
                </div>
            <% end%>
                <%= f.link_to_add t('acciones.asociar_cliente'), :users_clientes, class: 'btn btn-success js-anadir-uc margin-top20', onclick: 'select_disable_wait();'%>

              <button type="submit" class="btn btn-primary margin-top20"><%= t('botones.guardar')%>
                <i class="icon-arrow-right14 position-right"></i>
              </button>
            </div>
          </div>
      <% end %>
  <% end %>
</fieldset>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<%= render layout: "layouts/formcontainer_layout" do%>

  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12 col-lg-12 col-sm-12">
        <a href="<%= new_user_registration_path %>">
          <button type="button" class="btn btn-primary pull-right">
            <span class="" aria-hidden="true">
            </span>
            <%= t("acciones.nuevo") + ' ' + t("activerecord.models.users.one").downcase %>
          </button>
        </a>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="panel-body overflowed">
          <table class="table table-striped table-hover table-responsive-listados table-responsive table_custom1">
            <thead>
            <tr>
              <% model_user = @users.model %>
              <th><%= t("activerecord.models.users.one") %></th>
              <th class="text-center"><%= model_user.human_attribute_name :email %></th>
              <th class="text-center"><%= model_user.human_attribute_name :status %></th>
              <th class="text-center"><%= model_user.human_attribute_name :created_at %></th>
              <th class="text-center"><%= model_user.human_attribute_name :updated_at %></th>
              <th class="text-center"><%= model_user.human_attribute_name :logged_at %></th>
              <th class="text-center"><%= model_user.human_attribute_name :actions %></th>
            </tr>
            </thead>
            <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= user.username %></td>
                <td class="text-center"><%= user.email %></td>
                <td class="text-center">
                  <% if user.active? %>
                    <span class="glyphicon glyphicon-thumbs-up green"></span>
                  <% elsif user.down? %>
                    <span class="glyphicon glyphicon-thumbs-down red"></span>
                  <% end %>
                </td>
                <td class="text-center"><%= l( user.created_at, format: :default ) %></td>
                <td class="text-center"><%= l( user.updated_at, format: :default ) %></td>
                <td class="text-center"><%= l( user.current_sign_in_at, format: :default ) %></td>
                <td class="text-center">
                  <ul class="icons-list">
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="icon-menu9"></i>
                      </a>
                      <ul class="dropdown-menu dropdown-menu-right">

                        <li><%= link_to edit_user_path( user.id ) do %>
                              <i class="glyphicon glyphicon-edit"></i>
                              <%= t('botones.editar') %>
                          <% end %></li>
                        <% if user.active? %>
                            <li>
                            <%= link_to user_registration_path( user ), method: :delete, data: { confirm: t('acciones.confirmacion') }  do %>
                                <i class="glyphicon glyphicon-trash"></i>
                                  <%= t('botones.desactivar') %>
                            <% end %>
                              </li>
                        <% elsif  user.down? %>
                            <li>
                            <%= link_to reactivate_user_registration_path( user ), method: :put, data: { confirm: t('acciones.confirmacion') } do %>
                                <i class="glyphicon glyphicon-heart"></i>
                                  <%= t('botones.activar') %>
                            <% end %>
                              </li>
                        <% end %>

                      </ul>
                    </li>
                  </ul>
                </td>

              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

<% end %>